complete
devleague/Challenge-Multiples-of-3-and-5 pull request #20
Opened 2019-01-03 19:13 UTC by Alexithemia

2019-01-03 19:28 UTC, jaywon requested changes
Your solution is close but would not catch all cases. See if you can find out why! 🤔

2019-01-03 19:29 UTC, jaywon requested changes
Plz see comment.

2019-01-03 19:29 UTC, jaywon commented on multiples.js
> +  for (let i = 1; i < n; i++) {
Your solution won't catch all cases, see if you can find out why 🤔

2019-01-04 01:43 UTC, taesup approved these changes
LGTM! Closing PR.

2019-01-04 01:43 UTC, closed without merging